### PR TITLE
next: About display comment of sgf and read/write sgf with variation & Winrate.

### LINKED ISSUE #350: About display comment of sgf and read/write sgf with variation & Winrate.
First of all, I am very grateful for the amazing program.

It has helped me a lot.

However, I hope that can see the comments of the sgf when review the game, and I also hope to save the variation and Winrate.

I guess the author must be very busy, I can't wait and to try to make some minor changes.

1. Add the display the comment of the sgf (C tag): Forgive me very lazy, directly displayed under the variation panel, please ignore the ugly style :(
2. Add the ability to read and write the sgf with variation
3. By the way, write the Winrate in the comment of sgf for each step (C tag): Just a little try

Attached the codes and files, the code base on the release 0.5, and use the class (WrapString) of the Jim Menard. Thanks Jim Menard.
There are not many changes, not list the differences.

Just a reference for those in need.

Sorry for use the Issue because I can't find the author E-mail.
If not suitable, please remove it.

Looking forward to related functions of next release.

Thanks again.

### PR DESCRIPTION
**Pull request by zsalch**
Closes #350 

1. Add the display the comment of the sgf (C tag): Forgive me very lazy, directly displayed under the variation panel, please ignore the ugly style :(
2. Add the ability to read and write the sgf with variation
3. By the way, write the Winrate in the comment of sgf for each step (C tag): Just a little try

### CODE REVIEW

**Comment by zsalch** [comment]
new update:
fix the Winrate wrong when load the sgf with variation.

**Comment by featurecat** [comment]
sorry for the wait. I'll review this tomorrow!

**Comment by zsalch** [comment]
Thanks for your reply. Please ignore last commit (bd81db6: 2018/08/29 Multiple Weights Switching).
This is a pending change. I will discard the commit.

**Comment by OlivierBlanvillain** [comment]
@zsalch Could you please split this work into 3 distinct pull requests? Having everything in a single diff makes it hard to review.

Also, I personally dislike the idea of writing the win-rate in the SGF file. People have developed dedicated tools that might be better suited to do offline analysis of SGF files, it's not clear to me why this feature should be within the scope of Lizzie...

**Comment by zsalch** [comment]
@OlivierBlanvillain 
I got it and will split the pull request.

About writing win-rate, some people like do it. I'll default turn off the feature and change it to be a hidden option in the config.txt.

**Comment by zsalch** [comment]
Close this pull request and split two new pull request: #364 #365

**Comment by OlivierBlanvillain** [comment]
@zsalch Did you end up committing the winrate to comment feature? (#308)

**Pull request closed without merging**
