### PR TITLE
New board and background

### PR DESCRIPTION
**Pull request by ParmuzinAlexander**

### CODE REVIEW

**Comment by zsalch** [comment]
@featurecat @OlivierBlanvillain 
I think that in order to demo and guide users to use the new Theme, we should include an optional Theme when releasing the new version. What do you think?
@ParmuzinAlexander 
If so, could you like to provide an extra background, board and stone images that you like?

**Comment by OlivierBlanvillain** [comment]
@zsalch Sounds good! Should these additional images be added on top of the your theme PR?

**Comment by zsalch** [comment]
@ParmuzinAlexander 
Thanks. I will add to my theme PR.
But I don't know what the name is, can you give them a proper name?

**Comment by OlivierBlanvillain** [comment]
@zsalch Maybe you could also include in the sabaki images as well (with proper attribution)? As long as it's not the default, I think these would be good to have!

**Comment by ParmuzinAlexander** [comment]
@zsalch 
Theme name? If use one folder for everything images it will be easier to customization. Complete theme like "sabaki", "photorealistic" this is a step backwards.
Now "assets" and "theme" they have the same functionality. It would be logical remove "assets" and use only "theme" folder (contains all the pictures.).  And theme.txt transfer inside "ui" config.txt.

**Comment by zsalch** [comment]
@ParmuzinAlexander 
I mean, can you name your theme that includes you provided the images?

**Comment by ParmuzinAlexander** [comment]
@zsalch 
Yasnaya

**Comment by zsalch** [comment]
@ParmuzinAlexander 
I guess what you mean is that all the image files are placed in the theme folder, and the corresponding image is set in the theme.txt, such as yasnaya.txt, and the corresponding theme is specified as 'yasnaya ' in the config.txt file.
I want to know what is the advantage of this approach over the use of separate folder. I guess is it easy to maintain image files?

**Comment by ParmuzinAlexander** [comment]
@zsalch 
If user does not like some detail example background, it can change 1 character in config.txt  background3.png->background1.png without copying and replacing the real file. All files weigh only 1.4 Mb.
And I don't suggest using theme.txt or yasnaya.txt need just setting what texture to use in config.txt.

**Comment by OlivierBlanvillain** [comment]
I agree with you @ParmuzinAlexander, I feel that only having to update `config.txt` makes things simpler...

**Comment by zsalch** [comment]
The new Theme logic supports two ways for change option.
You can ignore the theme.txt and directly change option in the config.txt.

**Comment by OlivierBlanvillain** [comment]
Let's merge this for now and continue discussion on #378. @ParmuzinAlexander Thanks!

**Pull request merged**
