### PR TITLE
next: Fixed display issues

### PR DESCRIPTION
**Pull request by zsalch**
Issue #395 
Base on #378 #384 

It can support portrait mode, although it is not perfect, but it works.
In the portrait mode, the layout remains to be discussed, but I think it can help the current display.
Also fixed some display issues, when the user feels free to change the window size.

pm1
pm2
pm3

### CODE REVIEW

**Comment by AncalagonX** [comment]
If possible, it would be nice to make this a user-configurable setting to have it display above *or* below the board.

**Comment by OlivierBlanvillain** [comment]
I'm not really a fan of this solution as is doesn't fully solves the problem: people want to customize the layout. What about using something like [JToolBar](https://docs.oracle.com/javase/tutorial/uiswing/components/toolbar.html)? It seems like think can be moved around inside the main windows or even detached.

**Comment by zsalch** [comment]
I agree that this is just a transitional solution.
The best solution is that each panel can be customized, blended or separated.
It seems that JToolBar can implement, which may be the next goal.

**Comment by OlivierBlanvillain** [comment]
> I agree that this is just a transitional solution.

Then I would be for postponing this PR until we have a definitive solution...

**Comment by zsalch** [comment]
I no longer use this as a portrait mode solution, but just to solve some display issue, so I have changed the title.
Or I should close this, then wait for #402 to merge and re-open a PR that fixes the display issues.

**Pull request closed without merging**
