### PR TITLE
Revert "Fix NPE from getLocationOnScreen_NoTreeLock"

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
Reverts featurecat/lizzie#442

### CODE REVIEW

**Comment by featurecat** [comment]
sounds good

**Comment by featurecat** [comment]
what's the status. are you waiting for @zsalch? I would merge this if it's a problem.

**Comment by zsalch** [comment]
> what's the status. are you waiting for @zsalch? I would merge this if it's a problem.

This seems to be only a issue in the openjdk, the official jdk is no problem.

**Comment by zsalch** [comment]
If you want to solve this problem, I think it is necessary to separate the current panel. The board needs to be refreshed instantly, but other panels do not need it. Currently, the entire frame is refreshed, which causes many problems and limits many functions.
I'm already trying to make changes, and I'm currently finishing part of it. Maybe I will continue to push forward these two days and make a working version for everyone to discuss.

**Comment by featurecat** [comment]
Ok. I'll wait on merging this, then. Maybe we need to divide the UI into separate panels, because I am hoping to add a toolbar on the UI anyway. Which would probably want to be separate from the canvas object.

**Comment by featurecat** [comment]
Awaiting your solution.

**Comment by zsalch** [comment]
This PR can be merged, because it will restore previous wrong fix.

About the new panel, I'll submit a new PR.
I use the JWindow as the panel, because it can be drag to other monitors.

**Pull request merged**
