### PR TITLE
Fix NPE from getLocationOnScreen_NoTreeLock

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
This commit fixes the exception reported by @seopsx in #328.

### CODE REVIEW

**Comment by zsalch** [comment]
@OlivierBlanvillain 
If remove the `scrollPane.addNotify();`, the comment panel will draw wrong when mouse wheels:
image

**Comment by OlivierBlanvillain** [comment]
`addNotify` is not supposed to be called in user code, we need to find another way to do this...

[javadoc](https://docs.oracle.com/javase/6/docs/api/java/awt/Component.html#addNotify%28%29):
addNotify
Makes this Component displayable by connecting it to a native screen resource. This method is called internally by the toolkit and should not be called directly by programs.

**Comment by zsalch** [comment]
Yes, but it is a actual effective function.
Our final goal is to avoid current implementation of the comment.
Before that, I first tried to install Ubuntu to reproduce this error.

**Comment by OlivierBlanvillain** [comment]
> Our final goal is to avoid current implementation of the comment.

I assume you mean "to avoid breaking the current implementation...".
Sure, I totally agree. I think we should really stop merging PRs without reviewing them...

**Comment by featurecat** [comment]
Personally it seemed perfectly fine to me... I looked over it

**Comment by OlivierBlanvillain** [comment]
Also seemed fine to me, this is why it's best to have the person who touched the code last to have a look :smile:

**Comment by zsalch** [comment]
@OlivierBlanvillain 
> Our final goal is to avoid current implementation of the comment.
I actually mean that best way is change the method of the draw the comment of the sgf.
It takes some time, so I'm trying to solve the problem under Linux.

**Comment by zsalch** [comment]
I run the lizzie 0.6 on the Ubuntu 18.04 and Jdk 1.8.0_191, it seems ok:
image

**Comment by OlivierBlanvillain** [comment]
@zsalch It does run, but there is an exception printed in the console.

**Comment by zsalch** [comment]
No exception in my console, maybe the jdk version is different.

**Pull request merged**
